// GENERATED by campaign/build.py from campaign/missions/ep9.yaml — DO NOT EDIT.
// Act II Episode 9: Bolthole  (global.mission = 8)
//
// Loading this file a second time is safe, and is how the editor applies a
// change: the object and room indices are claimed once, everything else is
// re-bound. Re-entering the mission afterwards replays it from the new code.

// ---------------------------------------------------------------- dialogue
global.a2m1_t0 = "Captain, the Coalsack storm wall is dead ahead. Ratline beacons are dark again - we'll have to thread the lanes by eye.";
global.a2m1_t1 = "Storm cells are red clouds. They will damage any section inside them. Rogue asteroids drift through the lanes - evade them or destroy them.";
global.a2m1_t2 = "Follow the Ratlines# #Reach each dead beacon in sequence";
global.a2m1_t3 = "Beacon One confirmed, Captain. Four to go.";
global.a2m1_t4 = "Hull stress rising Captain! Recommend we keep to the lane.";
global.a2m1_t5 = "Storm surge! The lane behind us just closed. No turning back now.";
global.a2m1_t6 = "Last stretch Captain. Beacon Five is close.";
global.a2m1_t7 = "Unidentified contact, this is Bolthole Approach. You are inside the perimeter. Authenticate immediately or be fired upon.";
global.a2m1_t8 = "Transmitting authentication...";
global.a2m1_t9 = "Authentication confirmed. Guns to standby. Welcome home, Captain.";
global.a2m1_t10 = "Welcome back Captain. We were worried the storm had taken you.";
global.a2m1_t11 = "Reactor cores, medical supplies and the seed vault... You've bought Bolthole another year, Captain. The colony owes you their lives.";
global.a2m1_t12 = "Captain, stand by. Priority channel from the Admiralty.";
global.a2m1_t13 = "It's been a long time since Sol, old friend. Bring your ship alongside the naval yard. There's something I want you to see.";
global.a2m1_t14 = "She's been alongside you since the fifth beacon, Captain. Not one of your sensors saw her. We call her the Hestia X.";
global.a2m1_t15 = "Nineteen years ago I promised to keep the Alien device safe. I kept that promise - and my engineers kept busy. The cloak is drawn from Nanz wreckage. The shield is the same flux barrier that guarded Fleet HQ, small enough at last to fit a destroyer.";
global.a2m1_t16 = "Now listen carefully. The Nanz operate a station in the Vega sector - the same base Cherenkov stumbled on nineteen years ago. We never had the strength to go back. Now we have something better than strength. There is something aboard that station that can turn this war around, Captain, and we are going to steal it.";
global.a2m1_t17 = "An extraction team will ride with you. They know what they are looking for. You will not - and you will not ask. A secret is only safe when nobody who can be captured is carrying it.";
global.a2m1_t18 = "You have kept Bolthole's secret for nineteen years, Captain. Forgive me for keeping one from you.";
global.a2m1_t19 = "Report aboard the Hestia X";
global.a2m1_t20 = "Get some rest. You leave in eighteen hours. And Captain - the last free port in human space will be watching you go. Come back.";
global.a2m1_t21 = "Navigation computer restored. With your ship selected, right-click on any point in space to issue a move order.";
global.a2m1_t22 = "Your ship was destroyed!# #The critical supplies were lost.";

// ------------------------------------------------------------ editor state
// Three flags the editor drives, all mission-independent on purpose: only one
// mission is loaded at a time, and a per-mission name would mean mods/editor.gml
// had to know which mission it is talking to before it could set anything.
//
//   ed_edit   0 is the real game — storm cells bite, a lost ship fails the
//             mission. The editor raises it so a mission cannot be lost while
//             it is being written, and lowers it to test failure deliberately.
//   ed_pause  the editor's freeze. The stock sandbox pattern stops ships,
//             turrets and actors; it knows nothing about the storm object this
//             compiler invents, and that is the one generated thing whose Step
//             changes the world.
//   ed_beat   the playhead tracer: which rung last fired, and a counter that
//             also ticks on a re-entry, so a repeat of a rung is
//             distinguishable from a stall.
//
// None of them is reset by a reload — the mode belongs to the session.
if (!variable_global_exists('ed_edit')) global.ed_edit = 0;
if (!variable_global_exists('ed_pause')) global.ed_pause = 0;
if (!variable_global_exists('ed_beat')) { global.ed_beat = -1; global.ed_beatseq = 0; }

// Declared here rather than only in the controller's Create, because a hot
// reload re-binds the Draw event of a controller instance the *old* code
// created, and that instance never ran a Create that knew about this flag.
// Reading a global that does not exist aborts the action it is read in.
if (!variable_global_exists('a2m1_interf')) global.a2m1_interf = 0;


// ------------------------------------------------------------------- storm
// The storm is a painted mask, one cell per 50 world units: `#` damages,
// `@` damages harder, `.` is clear space. This is the only description of the
// storm in the file — the red wash, the gas clouds and the damage test are all
// read from these rows. What bites is the row, not the cloud: a puff is many
// cells wide, so the gas laps over clear space the mask says nothing about.
global.a2m1_cellsz = 50;
global.a2m1_cols = 100;
global.a2m1_rows = 40;
global.a2m1_d1 = 0.3;
global.a2m1_d2 = 0.4;
global.a2m1_dens = 0.18;
global.a2m1_mrow[0] = "...........................................#................##.........##############...............";
global.a2m1_mrow[1] = "........#.........#........................##...........................#############.....######....";
global.a2m1_mrow[2] = "##.################...........................#..........................###.#######....#########...";
global.a2m1_mrow[3] = "#....#@@@.....##.........####........@@@......................................#####....###########..";
global.a2m1_mrow[4] = "#....#@@@@@@.#.....@@@###...##.......@@@..............................................############..";
global.a2m1_mrow[5] = "#.....@@@@@@@......@@@#......#####...@@@..............................................#############.";
global.a2m1_mrow[6] = "#...####.@@@@......@@@................................................................#############.";
global.a2m1_mrow[7] = "#####...##@@@......##.............#...................................................##############";
global.a2m1_mrow[8] = "............@@@...##..............#...................................................##############";
global.a2m1_mrow[9] = "...........#@@@..##.#.............#.#..................................................#############";
global.a2m1_mrow[10] = ".........#.#@@@.##.##...............#...................................................############";
global.a2m1_mrow[11] = ".........###...##.##...............##.....................................................##########";
global.a2m1_mrow[12] = "...............#.#.................##......................................................#########";
global.a2m1_mrow[13] = "...............#...................##.......................................................########";
global.a2m1_mrow[14] = ".............@@@@...................#........................................................#######";
global.a2m1_mrow[15] = ".............@@@@............................................................................#######";
global.a2m1_mrow[16] = ".............@@@@............................................................................#######";
global.a2m1_mrow[17] = "..............#..............................................................................#######";
global.a2m1_mrow[18] = ".............#...............................................................................#######";
global.a2m1_mrow[19] = ".............#...............................................................................#######";
global.a2m1_mrow[20] = ".............#...............................................................................#######";
global.a2m1_mrow[21] = ".............................................................................................#######";
global.a2m1_mrow[22] = ".............................................#...............................................#######";
global.a2m1_mrow[23] = "............................#................................................................#######";
global.a2m1_mrow[24] = "...........................##...............#...............................................########";
global.a2m1_mrow[25] = "...........................##...............#...............................................########";
global.a2m1_mrow[26] = "...........................#.................#..............................................########";
global.a2m1_mrow[27] = "...........................#...............................................................#########";
global.a2m1_mrow[28] = "..........................#................#.#.............................................#########";
global.a2m1_mrow[29] = ".........................###.................#............................................##########";
global.a2m1_mrow[30] = ".#.......................####............................................................###########";
global.a2m1_mrow[31] = ".##......................#####..........................................................############";
global.a2m1_mrow[32] = ".##......................#...##............#...........................................#############";
global.a2m1_mrow[33] = "..#......................#####@@@.....................................................#############.";
global.a2m1_mrow[34] = "..#@@@.....................##.@@@..............##....................................##############.";
global.a2m1_mrow[35] = "..#@@@........................@@@..............@@@............................#####..##############.";
global.a2m1_mrow[36] = "..@@@@.........................##.............#@@@...........................#######.#############..";
global.a2m1_mrow[37] = "..@@@@#........##...#...........#.......#######@@@..........................#####################...";
global.a2m1_mrow[38] = "..@@@@.........####..............#..#####.................#####..#####......###################.....";
global.a2m1_mrow[39] = "..................................###....................##############.....##################......";

var stx_r, stx_c, stx_ch, stx_v, stx_c0;
for (stx_r = 0; stx_r < global.a2m1_rows; stx_r += 1) {
    for (stx_c = 0; stx_c < global.a2m1_cols; stx_c += 1) {
        stx_ch = string_char_at(global.a2m1_mrow[stx_r], stx_c + 1);
        stx_v = 0;
        if (stx_ch = "#") stx_v = 1;
        if (stx_ch = "@") stx_v = 2;
        global.a2m1_g[stx_r * global.a2m1_cols + stx_c] = stx_v;
    }
}
// Row runs. Nothing draws these — they are the sampling table a lightning
// strike picks its two endpoints from, which is why they are runs and not
// cells: one random pick lands anywhere in the storm, uniformly by area.
global.a2m1_nsp = 0;
for (stx_r = 0; stx_r < global.a2m1_rows; stx_r += 1) {
    stx_c0 = -1;
    for (stx_c = 0; stx_c <= global.a2m1_cols; stx_c += 1) {
        stx_v = 0;
        if (stx_c < global.a2m1_cols) stx_v = global.a2m1_g[stx_r * global.a2m1_cols + stx_c];
        if (stx_v > 0) {
            if (stx_c0 < 0) stx_c0 = stx_c;
        } else {
            if (stx_c0 >= 0) {
                global.a2m1_spx[global.a2m1_nsp] = stx_c0 * global.a2m1_cellsz;
                global.a2m1_spy[global.a2m1_nsp] = stx_r * global.a2m1_cellsz;
                global.a2m1_spw[global.a2m1_nsp] = (stx_c - stx_c0) * global.a2m1_cellsz;
                global.a2m1_nsp += 1;
                stx_c0 = -1;
            }
        }
    }
}

// ------------------------------------------------------------- define once
// GM7 has no room_delete, so a room_add per reload would leak one every time.
//
// One guard per index rather than one around the lot: a mod that grows a new
// object has to be able to claim it in a session that is already running, and a
// single `if (!variable_global_exists(ctr))` around everything would skip the
// new line forever on exactly the reload that needed it.
if (!variable_global_exists('a2m1_stormobj')) global.a2m1_stormobj = object_add();
if (!variable_global_exists('a2m1_puffobj')) global.a2m1_puffobj = object_add();
if (!variable_global_exists('a2m1_ctr')) {
global.a2m1_ctr = object_add();
global.act2_room1 = room_add();
room_set_code(global.act2_room1,
    'instance_create(0,0,ctr_GUI); instance_create(0,0,' + string(global.a2m1_ctr) + ');');
// The view is authored once and never re-asserted. mods/resolution.gml rewrites
// every room's view port at startup to the picked resolution -- that is how the
// drawing region gets built at anything other than 1024x768 -- so a reload that
// set this again would drop the mission room, and only the mission room, back to
// 4:3 inside a widescreen window.
room_set_view(global.act2_room1, 0, 1, 0, 0, 1024, 768, 0, 0, 1024, 768, 32, 32, -1, -1, -1);
room_set_view_enabled(global.act2_room1, 1);
}

// ------------------------------------------------------- re-bind every load
object_event_clear(global.a2m1_stormobj, 0, 0);
object_event_add(global.a2m1_stormobj, 0, 0,
    'depth = 700;' +
    'l_bolt = 0; l_flash = 0; l_bn = 0;' +
    'var sr, sc, sv, se, pd, pf;' +
    'for (sr = 0; sr < global.a2m1_rows; sr += 1) {' +
    'for (sc = 0; sc < global.a2m1_cols; sc += 1) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv > 0) {' +
    'se = 0;' +
    'if (sr = 0) se = 1;' +
    'if (sc = 0) se = 1;' +
    'if (sr = global.a2m1_rows - 1) se = 1;' +
    'if (sc = global.a2m1_cols - 1) se = 1;' +
    'if (se = 0) {' +
    'if (global.a2m1_g[(sr - 1) * global.a2m1_cols + sc] = 0) se = 1;' +
    'if (global.a2m1_g[(sr + 1) * global.a2m1_cols + sc] = 0) se = 1;' +
    'if (global.a2m1_g[sr * global.a2m1_cols + sc - 1] = 0) se = 1;' +
    'if (global.a2m1_g[sr * global.a2m1_cols + sc + 1] = 0) se = 1;' +
    '}' +
    'pd = global.a2m1_dens;' +
    'if (se = 1) pd = 0.5;' +
    'if (random(1) < pd) {' +
    'pf = instance_create(sc * global.a2m1_cellsz + random(global.a2m1_cellsz), sr * global.a2m1_cellsz + random(global.a2m1_cellsz), global.a2m1_puffobj);' +
    'if (sv = 2) pf.image_blend = make_color_rgb(255, 130 + random(60), 55 + random(45));' +
    '}' +
    '}' +
    '}' +
    '}' +
    'alarm[0] = 45 + random(90);');
object_event_clear(global.a2m1_stormobj, 3, 0);
object_event_add(global.a2m1_stormobj, 3, 0,
    'var sr, sc, sv;' +
    'if (global.ed_pause) exit;' +
    'if (l_bolt > 0) l_bolt -= 1;' +
    'if (l_flash > 0) l_flash -= 1;' +
    'if (global.ed_edit) exit;' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'with (ShipSection) {' +
    'if (l_owner = global.a2m1_ship) {' +
    'sr = floor(y / global.a2m1_cellsz);' +
    'sc = floor(x / global.a2m1_cellsz);' +
    'if (sr >= 0) { if (sr < global.a2m1_rows) { if (sc >= 0) { if (sc < global.a2m1_cols) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv = 1) damage(global.a2m1_d1, id);' +
    'if (sv = 2) damage(global.a2m1_d2, id);' +
    '} } } }' +
    '}' +
    '}' +
    'sr = floor(global.a2m1_ship.y / global.a2m1_cellsz);' +
    'sc = floor(global.a2m1_ship.x / global.a2m1_cellsz);' +
    'if (sr >= 0) { if (sr < global.a2m1_rows) { if (sc >= 0) { if (sc < global.a2m1_cols) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv = 1) damage(global.a2m1_d1, global.a2m1_ship);' +
    'if (sv = 2) damage(global.a2m1_d2, global.a2m1_ship);' +
    '} } } }' +
    '}');
object_event_clear(global.a2m1_stormobj, 8, 0);
object_event_add(global.a2m1_stormobj, 8, 0,
    'var vx, vy, vw, vh;' +
    'if (l_flash < 1) exit;' +
    'vx = view_xview[0]; vy = view_yview[0]; vw = view_wview[0]; vh = view_hview[0];' +
    'draw_set_blend_mode(bm_add);' +
    'with (global.a2m1_puffobj) {' +
    'if (x > vx - 500) { if (x < vx + vw + 500) { if (y > vy - 500) { if (y < vy + vh + 500) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,merge_color(image_blend,c_white,0.35),image_alpha * other.l_flash * 0.12);' +
    '} } } }' +
    '}' +
    'draw_set_alpha(1);' +
    'draw_set_blend_mode(bm_normal);');
object_event_clear(global.a2m1_puffobj, 0, 0);
object_event_add(global.a2m1_puffobj, 0, 0,
    'var ran;' +
    'sprite_index = spr_Nebula;' +
    'ran = random(1.2);' +
    'image_xscale = 1 + ran;' +
    'image_yscale = 1 + ran;' +
    'image_angle = random(360);' +
    'image_alpha = 0.13 + random(0.15);' +
    'image_blend = make_color_rgb(180 + random(75), 26 + random(46), 26 + random(34));' +
    'l_lo = image_alpha;' +
    'l_hi = image_alpha + 0.15;' +
    'l_glow = 0.004 + random(0.006);' +
    'l_rotate = -0.25 + random(0.5);' +
    'l_curl = 0.4 + random(0.9);' +
    'if (random(1) < 0.5) l_curl = -l_curl;' +
    'direction = random(360);' +
    'speed = 0.02 + random(0.06);' +
    'depth = 150 + random(260);' +
    'alarm[0] = 1 + random(9);');
object_event_clear(global.a2m1_puffobj, 2, 0);
object_event_add(global.a2m1_puffobj, 2, 0,
    'image_alpha += l_glow;' +
    'if (image_alpha < l_lo) { image_alpha = l_lo; l_glow *= -1; }' +
    'if (image_alpha > l_hi) { image_alpha = l_hi; l_glow *= -1; }' +
    'image_angle += l_rotate;' +
    'direction += l_curl;' +
    'alarm[0] = 9;');
object_event_clear(global.a2m1_puffobj, 8, 0);
object_event_add(global.a2m1_puffobj, 8, 0,
    'if (x < view_xview[0] - 500) exit;' +
    'if (x > view_xview[0] + view_wview[0] + 500) exit;' +
    'if (y < view_yview[0] - 500) exit;' +
    'if (y > view_yview[0] + view_hview[0] + 500) exit;' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha);');
object_event_clear(global.a2m1_stormobj, 2, 0);
object_event_add(global.a2m1_stormobj, 2, 0,
    'var i, tries, sx, sy, ex, ey, nx, ny, dd, got, k;' +
    'alarm[0] = 45 + random(90);' +
    'if (global.ed_pause) exit;' +
    'if (global.a2m1_nsp < 1) exit;' +
    'got = 0; sx = 0; sy = 0; ex = 0; ey = 0;' +
    'for (tries = 0; tries < 24; tries += 1) {' +
    'if (got < 2) {' +
    'i = floor(random(global.a2m1_nsp));' +
    'nx = global.a2m1_spx[i] + random(global.a2m1_spw[i]);' +
    'ny = global.a2m1_spy[i] + random(global.a2m1_cellsz);' +
    'if (nx > view_xview[0]) { if (nx < view_xview[0] + view_wview[0]) {' +
    'if (ny > view_yview[0]) { if (ny < view_yview[0] + view_hview[0]) {' +
    'if (got = 0) { sx = nx; sy = ny; got = 1; }' +
    'else {' +
    'dd = point_distance(sx, sy, nx, ny);' +
    'if (dd > 150) { if (dd < 550) { ex = nx; ey = ny; got = 2; } }' +
    '}' +
    '} } } }' +
    '}' +
    '}' +
    'if (got < 2) exit;' +
    'l_bn = 7;' +
    'l_bx[0] = sx; l_by[0] = sy;' +
    'for (k = 1; k < l_bn; k += 1) {' +
    'l_bx[k] = sx + (ex - sx) * k / l_bn - 30 + random(60);' +
    'l_by[k] = sy + (ey - sy) * k / l_bn - 30 + random(60);' +
    '}' +
    'l_bx[l_bn] = ex; l_by[l_bn] = ey;' +
    'l_bolt = 4 + random(3);' +
    'l_flash = 9;');
object_event_clear(global.a2m1_ctr, 0, 0);
object_event_add(global.a2m1_ctr, 0, 0,
    'var s;' +
    'depth = -9;' +
    'global.gamecontroller = self.id;' +
    'l_messagecount = 0;' +
    'l_seek = 0; l_seek_from = 0;' +
    'l_temp = -4;' +
    'global.ed_beat = -1; global.ed_beatseq += 1;' +
    'global.a2m1_won = 0; global.a2m1_failed = 0; global.a2m1_meteors = 0;' +
    'global.a2m1_interf = 0;' +
    'if !variable_global_exists("l_fnames") then' +
    '{' +
    'global.l_fnames = ds_list_create();' +
    'global.l_objects[0] = -4;' +
    '}' +
    'global.jumpinships = false;' +
    'global.a2m1_dmg[0] = noone; global.a2m1_dmgf[0] = 0.28;' +
    'global.a2m1_dmg[1] = noone; global.a2m1_dmgf[1] = 0.34;' +
    'global.a2m1_dmg[2] = noone; global.a2m1_dmgf[2] = 0.22;' +
    'global.a2m1_dmg[3] = noone; global.a2m1_dmgf[3] = 0.4;' +
    'alarm[6] = 60;' +
    'global.World_MaxRangeSqr = sqr(World_MaxRange);' +
    'stopMusic();' +
    's = instance_create(260,1000,Hestia);' +
    'global.a2m1_ship = s;' +
    'with (ShipSection) { if (l_owner = global.a2m1_ship) l_hp = l_hp * 0.55; }' +
    'repeat (16) { instance_create(random(room_width),random(room_height),ter_Nebula); }' +
    'instance_create(0,0,global.a2m1_stormobj);' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'alarm[2] = 45;');
object_event_clear(global.a2m1_ctr, 2, 2);
object_event_add(global.a2m1_ctr, 2, 2,
    'var s;' +
    'global.ed_beat = 0;' +
    'global.ed_beatseq += 1;' +
    'stopMusic();' +
    'sound_loop(snd_eeriesound);' +
    'global.a2m1_interf = 1;' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t21,spr_MesHint);');
object_event_clear(global.a2m1_ctr, 2, 5);
object_event_add(global.a2m1_ctr, 2, 5,
    'if (global.a2m1_meteors = 1) {' +
    'if (instance_number(obs_Meteor) < 48) {' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'var mm, px, py;' +
    'px = global.a2m1_ship.x; py = global.a2m1_ship.y;' +
    'mm = instance_create(px + 500 + random(300), py - 400 + random(800), obs_Meteor);' +
    'mm.direction = 150 + random(60);' +
    'mm.speed = 1 + random(1.2);' +
    'mm.image_xscale = 0.5 + random(0.4);' +
    'mm.image_yscale = mm.image_xscale;' +
    '}' +
    '}' +
    'alarm[5] = 35;' +
    '}');
object_event_clear(global.a2m1_ctr, 2, 6);
object_event_add(global.a2m1_ctr, 2, 6,
    'var i, k, f;' +
    'for (i = 0; i < 4; i += 1) {' +
    'k = global.a2m1_dmg[i];' +
    'f = global.a2m1_dmgf[i];' +
    'if (instance_exists(k)) {' +
    'k.l_syshp = 0;' +
    'with (ShipSection) {' +
    'if (l_owner = k) {' +
    'if (l_hp > l_maxhp * f) l_hp = l_maxhp * f;' +
    'k.l_syshp += l_hp;' +
    '}' +
    '}' +
    '}' +
    '}' +
    'alarm[6] = 60;');
object_event_clear(global.a2m1_ctr, 3, 0);
object_event_add(global.a2m1_ctr, 3, 0,
    'if (global.ed_edit) exit;' +
    'if (global.a2m1_won = 0) {' +
    'if (global.a2m1_failed = 0) {' +
    'if (!instance_exists(global.a2m1_ship)) {' +
    'global.a2m1_failed = 1;' +
    'centreCamera(global.lasteventx,global.lasteventy,0);' +
    'missionFail(global.a2m1_t22);' +
    '}' +
    '}' +
    '}');
object_event_clear(global.a2m1_ctr, 7, 10);
object_event_add(global.a2m1_ctr, 7, 10,
    'var g, s;' +
    'if (l_messagecount = 1) {' +
    'global.ed_beat = 1;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t0,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 2) {' +
    'global.ed_beat = 2;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t1,spr_MesHint);' +
    '}' +
    'else if (l_messagecount = 3) {' +
    'global.ed_beat = 3;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_meteors = 1; alarm[5] = 1;' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t2,spr_MesObj);' +
    'g = instance_create(724,1448,MoveToArea); g.l_target = global.a2m1_ship; showPing(724,1448);' +
    '}' +
    'else if (l_messagecount = 5) {' +
    'global.ed_beat = 5;' +
    'global.ed_beatseq += 1;' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t3,spr_MesMan1);' +
    'g = instance_create(1314,739,MoveToArea); g.l_target = global.a2m1_ship; showPing(1314,739);' +
    '}' +
    'else if (l_messagecount = 7) {' +
    'global.ed_beat = 7;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t4,spr_MesMan1);' +
    'g = instance_create(1911,1222,MoveToArea); g.l_target = global.a2m1_ship; showPing(1911,1222);' +
    '}' +
    'else if (l_messagecount = 9) {' +
    'global.ed_beat = 9;' +
    'global.ed_beatseq += 1;' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t5,spr_MesMan1);' +
    'g = instance_create(2269,741,MoveToArea); g.l_target = global.a2m1_ship; showPing(2269,741);' +
    '}' +
    'else if (l_messagecount = 11) {' +
    'global.ed_beat = 11;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t6,spr_MesMan1);' +
    'g = instance_create(2520,1120,MoveToArea); g.l_target = global.a2m1_ship; showPing(2520,1120);' +
    '}' +
    'else if (l_messagecount = 13) {' +
    'global.ed_beat = 13;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,c_red,"Bolthole Approach",global.a2m1_t7,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 14) {' +
    'global.ed_beat = 14;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t8,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 15) {' +
    'global.ed_beat = 15;' +
    'global.ed_beatseq += 1;' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'global.a2m1_meteors = 0;' +
    'showMessage(0,$00FF00,"Bolthole Approach",global.a2m1_t9,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 16) {' +
    'global.ed_beat = 16;' +
    'global.ed_beatseq += 1;' +
    'stopMusic(); bgm_Play(global.mus_theme,1);' +
    'sound_stop(snd_eeriesound);' +
    'global.a2m1_interf = 0;' +
    'centreCamera(3437,917,90);' +
    'global.lasteventx = 3437; global.lasteventy = 917;' +
    'global.a2m1_station = noone;' +
    'if (file_exists("mods/ships/station_bolthole.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/station_bolthole.shp",2,3409,1102);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_station = instance_create(3409,1102,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_station)) { global.a2m1_station.l_holdposition = true; global.a2m1_station.l_myship = 0; global.a2m1_station.l_thrust = 0; global.a2m1_station.l_maxspeed = 0; global.a2m1_station.l_turning = 0; global.a2m1_station.direction = 90; global.a2m1_station.image_angle = 90; };' +
    'instance_create(3095,461,ter_Planet);' +
    'global.a2m1_berth1 = instance_create(2930,707,Hecate); global.a2m1_berth1.l_holdposition = true; global.a2m1_berth1.l_myship = 0; global.a2m1_berth1.l_thrust = 0; global.a2m1_berth1.l_maxspeed = 0; global.a2m1_berth1.l_turning = 0; global.a2m1_berth1.direction = 270; global.a2m1_berth1.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth1) l_hp = l_hp * 0.28; }; global.a2m1_dmg[0] = global.a2m1_berth1;' +
    'global.a2m1_berth2 = instance_create(3129,775,Cronus); global.a2m1_berth2.l_holdposition = true; global.a2m1_berth2.l_myship = 0; global.a2m1_berth2.l_thrust = 0; global.a2m1_berth2.l_maxspeed = 0; global.a2m1_berth2.l_turning = 0; global.a2m1_berth2.direction = 270; global.a2m1_berth2.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth2) l_hp = l_hp * 0.34; }; global.a2m1_dmg[1] = global.a2m1_berth2;' +
    'global.a2m1_berth3 = instance_create(3700,707,Athena); global.a2m1_berth3.l_holdposition = true; global.a2m1_berth3.l_myship = 0; global.a2m1_berth3.l_thrust = 0; global.a2m1_berth3.l_maxspeed = 0; global.a2m1_berth3.l_turning = 0; global.a2m1_berth3.direction = 270; global.a2m1_berth3.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth3) l_hp = l_hp * 0.22; }; global.a2m1_dmg[2] = global.a2m1_berth3;' +
    'global.a2m1_berth4 = instance_create(3877,800,Hestia); global.a2m1_berth4.l_holdposition = true; global.a2m1_berth4.l_myship = 0; global.a2m1_berth4.l_thrust = 0; global.a2m1_berth4.l_maxspeed = 0; global.a2m1_berth4.l_turning = 0; global.a2m1_berth4.direction = 270; global.a2m1_berth4.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth4) l_hp = l_hp * 0.4; }; global.a2m1_dmg[3] = global.a2m1_berth4;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t10,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 17) {' +
    'global.ed_beat = 17;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t11,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 18) {' +
    'global.ed_beat = 18;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t12,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 19) {' +
    'global.ed_beat = 19;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t13,spr_MesHong);' +
    'g = instance_create(3387,825,MoveToArea); g.l_target = global.a2m1_ship; showPing(3387,825);' +
    '}' +
    'else if (l_messagecount = 21) {' +
    'global.ed_beat = 21;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_hestiax = instance_create(3384,701,Hestia);' +
    'showPing(3384,701);' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t14,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 22) {' +
    'global.ed_beat = 22;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t15,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 23) {' +
    'global.ed_beat = 23;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t16,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 24) {' +
    'global.ed_beat = 24;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t17,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 25) {' +
    'global.ed_beat = 25;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t18,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 26) {' +
    'global.ed_beat = 26;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t19,spr_MesObj);' +
    '}' +
    'else if (l_messagecount = 27) {' +
    'global.ed_beat = 27;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t20,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 28) {' +
    'global.ed_beat = 28;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_won = 1; missionSucc();' +
    '}');
object_event_clear(global.a2m1_ctr, 7, 11);
object_event_add(global.a2m1_ctr, 7, 11,
    'var s;' +
    'if (l_seek >= 3) { if (l_seek_from < 3) {' +
    'global.a2m1_meteors = 1; alarm[5] = 1;' +
    '} }' +
    'if (l_seek >= 15) { if (l_seek_from < 15) {' +
    'global.a2m1_meteors = 0;' +
    '} }' +
    'if (l_seek >= 16) { if (l_seek_from < 16) {' +
    'stopMusic(); bgm_Play(global.mus_theme,1);' +
    'sound_stop(snd_eeriesound);' +
    'global.a2m1_interf = 0;' +
    'centreCamera(3437,917,90);' +
    'global.lasteventx = 3437; global.lasteventy = 917;' +
    'global.a2m1_station = noone;' +
    'if (file_exists("mods/ships/station_bolthole.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/station_bolthole.shp",2,3409,1102);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_station = instance_create(3409,1102,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_station)) { global.a2m1_station.l_holdposition = true; global.a2m1_station.l_myship = 0; global.a2m1_station.l_thrust = 0; global.a2m1_station.l_maxspeed = 0; global.a2m1_station.l_turning = 0; global.a2m1_station.direction = 90; global.a2m1_station.image_angle = 90; };' +
    'instance_create(3095,461,ter_Planet);' +
    'global.a2m1_berth1 = instance_create(2930,707,Hecate); global.a2m1_berth1.l_holdposition = true; global.a2m1_berth1.l_myship = 0; global.a2m1_berth1.l_thrust = 0; global.a2m1_berth1.l_maxspeed = 0; global.a2m1_berth1.l_turning = 0; global.a2m1_berth1.direction = 270; global.a2m1_berth1.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth1) l_hp = l_hp * 0.28; }; global.a2m1_dmg[0] = global.a2m1_berth1;' +
    'global.a2m1_berth2 = instance_create(3129,775,Cronus); global.a2m1_berth2.l_holdposition = true; global.a2m1_berth2.l_myship = 0; global.a2m1_berth2.l_thrust = 0; global.a2m1_berth2.l_maxspeed = 0; global.a2m1_berth2.l_turning = 0; global.a2m1_berth2.direction = 270; global.a2m1_berth2.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth2) l_hp = l_hp * 0.34; }; global.a2m1_dmg[1] = global.a2m1_berth2;' +
    'global.a2m1_berth3 = instance_create(3700,707,Athena); global.a2m1_berth3.l_holdposition = true; global.a2m1_berth3.l_myship = 0; global.a2m1_berth3.l_thrust = 0; global.a2m1_berth3.l_maxspeed = 0; global.a2m1_berth3.l_turning = 0; global.a2m1_berth3.direction = 270; global.a2m1_berth3.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth3) l_hp = l_hp * 0.22; }; global.a2m1_dmg[2] = global.a2m1_berth3;' +
    'global.a2m1_berth4 = instance_create(3877,800,Hestia); global.a2m1_berth4.l_holdposition = true; global.a2m1_berth4.l_myship = 0; global.a2m1_berth4.l_thrust = 0; global.a2m1_berth4.l_maxspeed = 0; global.a2m1_berth4.l_turning = 0; global.a2m1_berth4.direction = 270; global.a2m1_berth4.image_angle = 270; with (ShipSection) { if (l_owner = global.a2m1_berth4) l_hp = l_hp * 0.4; }; global.a2m1_dmg[3] = global.a2m1_berth4;' +
    '} }' +
    'if (l_seek >= 21) { if (l_seek_from < 21) {' +
    'global.a2m1_hestiax = instance_create(3384,701,Hestia);' +
    '} }' +
    'l_seek_from = l_seek;' +
    'global.ed_beat = l_seek;' +
    'global.ed_beatseq += 1;' +
    'if (l_seek = 1) l_messagecount = 2;' +
    'else if (l_seek = 2) l_messagecount = 3;' +
    'else if (l_seek = 3) l_messagecount = 5;' +
    'else if (l_seek = 5) l_messagecount = 7;' +
    'else if (l_seek = 7) l_messagecount = 9;' +
    'else if (l_seek = 9) l_messagecount = 11;' +
    'else if (l_seek = 11) l_messagecount = 13;' +
    'else if (l_seek = 13) l_messagecount = 14;' +
    'else if (l_seek = 14) l_messagecount = 15;' +
    'else if (l_seek = 15) l_messagecount = 16;' +
    'else if (l_seek = 16) l_messagecount = 17;' +
    'else if (l_seek = 17) l_messagecount = 18;' +
    'else if (l_seek = 18) l_messagecount = 19;' +
    'else if (l_seek = 19) l_messagecount = 21;' +
    'else if (l_seek = 21) l_messagecount = 22;' +
    'else if (l_seek = 22) l_messagecount = 23;' +
    'else if (l_seek = 23) l_messagecount = 24;' +
    'else if (l_seek = 24) l_messagecount = 25;' +
    'else if (l_seek = 25) l_messagecount = 26;' +
    'else if (l_seek = 26) l_messagecount = 27;' +
    'else if (l_seek = 27) l_messagecount = 28;' +
    'else if (l_seek = 28) l_messagecount = 29;');
object_event_clear(global.a2m1_ctr, 8, 0);
object_event_add(global.a2m1_ctr, 8, 0,
    'var vx, vy, vw, vh, i;' +
    'vx = view_xview[0]; vy = view_yview[0]; vw = view_wview[0]; vh = view_hview[0];' +
    'with (global.a2m1_stormobj) {' +
    'if (l_bolt > 0) {' +
    'draw_set_blend_mode(bm_add);' +
    'draw_set_color(make_color_rgb(255, 70, 55));' +
    'draw_set_alpha(0.20);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 24); }' +
    'draw_set_color(make_color_rgb(255, 140, 110));' +
    'draw_set_alpha(0.45);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 8); }' +
    'draw_set_color(make_color_rgb(255, 242, 228));' +
    'draw_set_alpha(0.95);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 2); }' +
    'draw_set_alpha(1);' +
    'draw_set_blend_mode(bm_normal);' +
    '}' +
    '}' +
    'if (global.a2m1_interf = 0) exit;' +
    'draw_set_blend_mode(bm_add);' +
    'with (ter_Nebula) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha + random(0.4));' +
    '}' +
    'with (global.a2m1_puffobj) {' +
    'if (x > vx - 500) { if (x < vx + vw + 500) { if (y > vy - 500) { if (y < vy + vh + 500) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha * (0.6 + random(0.9)));' +
    '} } } }' +
    '}' +
    'draw_set_blend_mode(bm_normal);' +
    'with (ShipSection) {' +
    'draw_sprite_ext(sprite_index,image_index,xprevious - 4 + random(8),yprevious - 4 + random(8),image_xscale * (1 + random(0.22)),image_yscale * (1 + random(0.22)),image_angle,l_colour,image_alpha / 2);' +
    '}');

room_set_width(global.act2_room1, 5000);
room_set_height(global.act2_room1, 2000);
room_set_caption(global.act2_room1, "Bolthole");
room_set_background_color(global.act2_room1, c_black, 1);
