// GENERATED by campaign/build.py from campaign/missions/ep9.yaml — DO NOT EDIT.
// Act II Episode 9: Bolthole  (global.mission = 8)
if (variable_global_exists('a2m1_init')) exit;
global.a2m1_init = 1;

// ---------------------------------------------------------------- dialogue
global.a2m1_t0 = "Captain, the Coalsack storm wall is dead ahead. Ratline beacons are dark again - we'll have to thread the lanes by eye.";
global.a2m1_t1 = "Storm cells are marked in red. They will damage any section inside them. Rogue asteroids drift through the lanes - evade them or destroy them.";
global.a2m1_t2 = "Follow the Ratlines# #Reach each dead beacon in sequence";
global.a2m1_t3 = "Beacon One confirmed, Captain. Four to go.";
global.a2m1_t4 = "Hull stress rising Captain! Recommend we keep to the lane.";
global.a2m1_t5 = "Storm surge! The lane behind us just closed. No turning back now.";
global.a2m1_t6 = "Last stretch Captain. Beacon Five is close.";
global.a2m1_t7 = "Unidentified contact, this is Bolthole Approach. You are inside the perimeter. Authenticate immediately or be fired upon.";
global.a2m1_t8 = "Transmitting authentication...";
global.a2m1_t9 = "Authentication confirmed. Guns to standby. Welcome home, Captain.";
global.a2m1_t10 = "Welcome back Captain. We were worried the storm had taken you.";
global.a2m1_t11 = "Reactor cores, medical supplies and the seed vault... You've bought Bolthole another year, Captain. The colony owes you their lives.";
global.a2m1_t12 = "Captain, stand by. Priority channel from the Admiralty.";
global.a2m1_t13 = "It's been a long time since Sol, old friend. Bring your ship alongside the naval yard. There's something I want you to see.";
global.a2m1_t14 = "She's been alongside you since the fifth beacon, Captain. Not one of your sensors saw her. We call her the Hestia X.";
global.a2m1_t15 = "Nineteen years ago I promised to keep the Alien device safe. I kept that promise - and my engineers kept busy. The cloak is drawn from Nanz wreckage. The shield is the same flux barrier that guarded Fleet HQ, small enough at last to fit a destroyer.";
global.a2m1_t16 = "Now listen carefully. The Nanz operate a station in the Vega sector - the same base Cherenkov stumbled on nineteen years ago. We never had the strength to go back. Now we have something better than strength. There is something aboard that station that can turn this war around, Captain, and we are going to steal it.";
global.a2m1_t17 = "An extraction team will ride with you. They know what they are looking for. You will not - and you will not ask. A secret is only safe when nobody who can be captured is carrying it.";
global.a2m1_t18 = "You have kept Bolthole's secret for nineteen years, Captain. Forgive me for keeping one from you.";
global.a2m1_t19 = "Report aboard the Hestia X";
global.a2m1_t20 = "Get some rest. You leave in eighteen hours. And Captain - the last free port in human space will be watching you go. Come back.";
global.a2m1_t21 = "Navigation computer restored. With your ship selected, right-click on any point in space to issue a move order.";
global.a2m1_t22 = "Your ship was destroyed!# #The critical supplies were lost.";

// ------------------------------------------------------------- storm cells
var zo;
zo = object_add();
global.a2m1_zoneobj = zo;
object_event_add(zo, 0, 0, 'l_r = 200; l_dmg = 0.3; depth = 9000;');
object_event_add(zo, 3, 0,
    'if (instance_exists(global.a2m1_ship)) {' +
    'with (ShipSection) {' +
    'if (l_owner = global.a2m1_ship) {' +
    'if (point_distance(x,y,other.x,other.y) < other.l_r) {' +
    'l_hp -= other.l_dmg;' +
    '}' +
    '}' +
    '}' +
    '}');
object_event_add(zo, 8, 0,
    'draw_set_blend_mode(bm_add);' +
    'draw_set_color(c_red);' +
    'draw_set_alpha(0.10);' +
    'draw_circle(x,y,l_r,0);' +
    'draw_set_alpha(0.30);' +
    'draw_circle(x,y,l_r,1);' +
    'draw_set_alpha(1);' +
    'draw_set_blend_mode(bm_normal);');

// -------------------------------------------------------------- controller
var c;
c = object_add();
global.a2m1_ctr = c;
object_event_add(c, 0, 0,
    'var s, z;' +
    'global.gamecontroller = self.id;' +
    'l_messagecount = 0;' +
    'l_temp = -4;' +
    'global.a2m1_won = 0; global.a2m1_failed = 0; global.a2m1_meteors = 0;' +
    'global.World_MaxRangeSqr = sqr(World_MaxRange);' +
    'stopMusic();' +
    's = instance_create(260,1000,Hestia);' +
    'global.a2m1_ship = s;' +
    'with (ShipSection) { if (l_owner = global.a2m1_ship) l_hp = l_hp * 0.55; }' +
    'repeat (16) { instance_create(random(room_width),random(room_height),ter_Nebula); }' +
    'z = instance_create(950,520,global.a2m1_zoneobj); z.l_r = 240; z.l_dmg = 0.3;' +
    'z = instance_create(1180,1520,global.a2m1_zoneobj); z.l_r = 280; z.l_dmg = 0.3;' +
    'z = instance_create(1700,700,global.a2m1_zoneobj); z.l_r = 260; z.l_dmg = 0.3;' +
    'z = instance_create(2050,1350,global.a2m1_zoneobj); z.l_r = 240; z.l_dmg = 0.3;' +
    'z = instance_create(1450,1050,global.a2m1_zoneobj); z.l_r = 170; z.l_dmg = 0.4;' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'alarm[2] = 45;');
object_event_add(c, 2, 2,
    'stopMusic();' +
    'sound_loop(snd_eeriesound);' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t21,spr_MesHint);');
object_event_add(c, 2, 5,
    'if (global.a2m1_meteors = 1) {' +
    'if (instance_number(obs_Meteor) < 8) {' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'var mm, px, py;' +
    'px = global.a2m1_ship.x; py = global.a2m1_ship.y;' +
    'mm = instance_create(px + 500 + random(300), py - 400 + random(800), obs_Meteor);' +
    'mm.direction = 150 + random(60);' +
    'mm.speed = 1 + random(1.2);' +
    'mm.image_xscale = 0.5 + random(0.4);' +
    'mm.image_yscale = mm.image_xscale;' +
    '}' +
    '}' +
    'alarm[5] = 210;' +
    '}');
object_event_add(c, 3, 0,
    'if (global.a2m1_won = 0) {' +
    'if (global.a2m1_failed = 0) {' +
    'if (!instance_exists(global.a2m1_ship)) {' +
    'global.a2m1_failed = 1;' +
    'centreCamera(global.lasteventx,global.lasteventy,0);' +
    'missionFail(global.a2m1_t22);' +
    '}' +
    '}' +
    '}');
object_event_add(c, 7, 10,
    'var g;' +
    'if (l_messagecount = 1) {' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t0,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 2) {' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t1,spr_MesHint);' +
    '}' +
    'else if (l_messagecount = 3) {' +
    'global.a2m1_meteors = 1; alarm[5] = 1;' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t2,spr_MesObj);' +
    'g = instance_create(760,1180,MoveToArea); g.l_target = global.a2m1_ship; showPing(760,1180);' +
    '}' +
    'else if (l_messagecount = 5) {' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t3,spr_MesMan1);' +
    'g = instance_create(1230,780,MoveToArea); g.l_target = global.a2m1_ship; showPing(1230,780);' +
    '}' +
    'else if (l_messagecount = 7) {' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t4,spr_MesMan1);' +
    'g = instance_create(1660,1180,MoveToArea); g.l_target = global.a2m1_ship; showPing(1660,1180);' +
    '}' +
    'else if (l_messagecount = 9) {' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t5,spr_MesMan1);' +
    'g = instance_create(2120,860,MoveToArea); g.l_target = global.a2m1_ship; showPing(2120,860);' +
    '}' +
    'else if (l_messagecount = 11) {' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t6,spr_MesMan1);' +
    'g = instance_create(2520,1120,MoveToArea); g.l_target = global.a2m1_ship; showPing(2520,1120);' +
    '}' +
    'else if (l_messagecount = 13) {' +
    'showMessage(0,c_red,"Bolthole Approach",global.a2m1_t7,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 14) {' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t8,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 15) {' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'global.a2m1_meteors = 0;' +
    'showMessage(0,$00FF00,"Bolthole Approach",global.a2m1_t9,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 16) {' +
    'stopMusic(); bgm_Play(global.mus_theme,1);' +
    'sound_stop(snd_eeriesound);' +
    'centreCamera(2760,1050,90);' +
    'global.lasteventx = 2760; global.lasteventy = 1050;' +
    'global.a2m1_station = instance_create(2760,1050,SpaceStation);' +
    'instance_create(2900,860,ter_Planet);' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t10,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 17) {' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t11,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 18) {' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t12,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 19) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t13,spr_MesHong);' +
    'g = instance_create(2680,1140,MoveToArea); g.l_target = global.a2m1_ship; showPing(2680,1140);' +
    '}' +
    'else if (l_messagecount = 21) {' +
    'global.a2m1_hestiax = instance_create(2610,1210,Hestia);' +
    'showPing(2610,1210);' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t14,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 22) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t15,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 23) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t16,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 24) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t17,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 25) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t18,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 26) {' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t19,spr_MesObj);' +
    '}' +
    'else if (l_messagecount = 27) {' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t20,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 28) {' +
    'global.a2m1_won = 1; missionSucc();' +
    '}');

// -------------------------------------------------------------------- room
var r;
r = room_add();
room_set_width(r, 3000);
room_set_height(r, 2000);
room_set_caption(r, "Bolthole");
room_set_background_color(r, c_black, 1);
room_set_view(r, 0, 1, 0, 0, 1024, 768, 0, 0, 1024, 768, 32, 32, -1, -1, -1);
room_set_view_enabled(r, 1);
room_set_code(r, 'instance_create(0,0,ctr_GUI); instance_create(0,0,' + string(c) + ');');
global.act2_room1 = r;
