// GENERATED by campaign/build.py from campaign/missions/ep9.yaml — DO NOT EDIT.
// Act II Episode 9: Bolthole  (global.mission = 8)
//
// Loading this file a second time is safe, and is how the editor applies a
// change: the object and room indices are claimed once, everything else is
// re-bound. Re-entering the mission afterwards replays it from the new code.

// ---------------------------------------------------------------- dialogue
global.a2m1_t0 = "Captain, the Coalsack storm wall is dead ahead. Ratline beacons are dark again - we'll have to thread the lanes by eye.";
global.a2m1_t1 = "Storm cells are red clouds. They will damage any section inside them. Rogue asteroids drift through the lanes - evade them or destroy them.";
global.a2m1_t2 = "Follow the Ratlines# #Reach each dead beacon in sequence";
global.a2m1_t3 = "Beacon One confirmed, Captain. Four to go.";
global.a2m1_t4 = "Hull stress rising Captain! Recommend we keep to the lane.";
global.a2m1_t5 = "Storm surge! The lane behind us just closed. No turning back now.";
global.a2m1_t6 = "Last stretch Captain. Beacon Five is close.";
global.a2m1_t7 = "Unidentified contact, this is Bolthole Approach. You are inside the perimeter. Authenticate immediately or be fired upon.";
global.a2m1_t8 = "Transmitting authentication...";
global.a2m1_t9 = "Authentication confirmed. Guns to standby. Welcome home, Captain.";
global.a2m1_t10 = "Welcome back Captain. We were worried the storm had taken you.";
global.a2m1_t11 = "Reactor cores, medical supplies and the seed vault... You've bought Bolthole another year, Captain. The colony owes you their lives.";
global.a2m1_t12 = "Captain, stand by. Priority channel from the Admiralty.";
global.a2m1_t13 = "It's been a long time since Sol, old friend. Bring your ship alongside the naval yard. There's something I want you to see.";
global.a2m1_t14 = "She's been alongside you since the fifth beacon, Captain. Not one of your sensors saw her. We call her the Hestia X.";
global.a2m1_t15 = "Nineteen years ago I promised to keep the Alien device safe. I kept that promise - and my engineers kept busy. The cloak is drawn from Nanz wreckage. The shield is the same flux barrier that guarded Fleet HQ, small enough at last to fit a destroyer.";
global.a2m1_t16 = "Now listen carefully. The Nanz operate a station in the Vega sector - the same base Cherenkov stumbled on nineteen years ago. We never had the strength to go back. Now we have something better than strength. There is something aboard that station that can turn this war around, Captain, and we are going to steal it.";
global.a2m1_t17 = "An extraction team will ride with you. They know what they are looking for. You will not - and you will not ask. A secret is only safe when nobody who can be captured is carrying it.";
global.a2m1_t18 = "You have kept Bolthole's secret for nineteen years, Captain. Forgive me for keeping one from you.";
global.a2m1_t19 = "Report aboard the Hestia X";
global.a2m1_t20 = "Get some rest. You leave in eighteen hours. And Captain - the last free port in human space will be watching you go. Come back.";
global.a2m1_t21 = "Navigation computer restored. With your ship selected, right-click on any point in space to issue a move order.";
global.a2m1_t22 = "Your ship was destroyed!# #The critical supplies were lost.";

// ------------------------------------------------------------ editor state
// Three flags the editor drives, all mission-independent on purpose: only one
// mission is loaded at a time, and a per-mission name would mean mods/editor.gml
// had to know which mission it is talking to before it could set anything.
//
//   ed_edit   0 is the real game — storm cells bite, a lost ship fails the
//             mission. The editor raises it so a mission cannot be lost while
//             it is being written, and lowers it to test failure deliberately.
//   ed_pause  the editor's freeze. The stock sandbox pattern stops ships,
//             turrets and actors; it knows nothing about the storm object this
//             compiler invents, and that is the one generated thing whose Step
//             changes the world.
//   ed_beat   the playhead tracer: which rung last fired, and a counter that
//             also ticks on a re-entry, so a repeat of a rung is
//             distinguishable from a stall.
//
// None of them is reset by a reload — the mode belongs to the session.
if (!variable_global_exists('ed_edit')) global.ed_edit = 0;
if (!variable_global_exists('ed_pause')) global.ed_pause = 0;
if (!variable_global_exists('ed_beat')) { global.ed_beat = -1; global.ed_beatseq = 0; }

// Declared here rather than only in the controller's Create, because a hot
// reload re-binds the Draw event of a controller instance the *old* code
// created, and that instance never ran a Create that knew about this flag.
// Reading a global that does not exist aborts the action it is read in.
if (!variable_global_exists('a2m1_interf')) global.a2m1_interf = 0;
if (!variable_global_exists('a2m1_interfc')) global.a2m1_interfc = 0;


// ------------------------------------------------------------------- storm
// The storm is a painted mask, one cell per 50 world units: `#` damages,
// `@` damages harder, `.` is clear space. This is the only description of the
// storm in the file — the red wash, the gas clouds and the damage test are all
// read from these rows. What bites is the row, not the cloud: a puff is many
// cells wide, so the gas laps over clear space the mask says nothing about.
global.a2m1_cellsz = 50;
global.a2m1_cols = 112;
global.a2m1_rows = 40;
global.a2m1_d1 = 0.3;
global.a2m1_d2 = 0.4;
global.a2m1_dens = 0.18;
global.a2m1_mrow[0] = "...........................................#..@@@@@@@@@@@@@@@@@##......#@@@@@......############@@@@@@...........";
global.a2m1_mrow[1] = "........#.........#....................###.###@@@@@@@@@@@@@@@@@###.....##@@@........#############@@@@@######....";
global.a2m1_mrow[2] = "##.################...................#####..##@@@@@@@@@@@@@@@####.....#####.................###.@@@@@#######...";
global.a2m1_mrow[3] = "#....#@@@.....##.........####........@#####..########################...###......................@@@@@########..";
global.a2m1_mrow[4] = "#....#@@@@@@.#.....@@@###...##.......@#####...###############.########............................@@@#########..";
global.a2m1_mrow[5] = "#.....@@@@@@@......@@@#......#####...@@###.......................#####............................#######@@@###.";
global.a2m1_mrow[6] = "#...####.@@@@......@@@...........................................#####............................######@@@@@##.";
global.a2m1_mrow[7] = "#####...##@@@......##.............#...............................###.............................######@@@@@###";
global.a2m1_mrow[8] = "............@@@...##..............#...............................................................######@@@@@###";
global.a2m1_mrow[9] = "...........#@@@..##.#.............#.#..............................................................#####@@@@@###";
global.a2m1_mrow[10] = ".........#.#@@@.##.##...............#...............................................................####@@@@@###";
global.a2m1_mrow[11] = ".........###...##.##...............##.................................................................##@@@@@###";
global.a2m1_mrow[12] = "...............#.#.................##..................................................................##@@@####";
global.a2m1_mrow[13] = "...............#...................##...................................................................########";
global.a2m1_mrow[14] = ".............@@@@...................#....................................................................#######";
global.a2m1_mrow[15] = ".............@@@@........................................................................................#######";
global.a2m1_mrow[16] = ".............@@@@........................................................................................#######";
global.a2m1_mrow[17] = "..............#..........................................................................................#######";
global.a2m1_mrow[18] = ".............#...........................................................................................#######";
global.a2m1_mrow[19] = ".............#...........................................................................................#######";
global.a2m1_mrow[20] = ".............#...........................................................................................#@@@###";
global.a2m1_mrow[21] = ".........................................................................................................@@@@@##";
global.a2m1_mrow[22] = ".............................................#...........................................................@@@@@##";
global.a2m1_mrow[23] = "............................#............................................................................@@@@@##";
global.a2m1_mrow[24] = "...........................##...............#...........................................................#@@@@@##";
global.a2m1_mrow[25] = "...........................##...............#...........................................................#@@@@@##";
global.a2m1_mrow[26] = "...........................#.................#..........................................................@@@@@@##";
global.a2m1_mrow[27] = "...........................#...........................................................................#@@@@@###";
global.a2m1_mrow[28] = "..........................#................#.#.........................................................#@@@@@###";
global.a2m1_mrow[29] = ".........................###.................#........................................................##@@@@@###";
global.a2m1_mrow[30] = ".#.......................####........................................................................##@@@@@@###";
global.a2m1_mrow[31] = ".##......................#####......................................................................###@@@@@####";
global.a2m1_mrow[32] = ".##......................#...##............#.......................................................###@@@@@@####";
global.a2m1_mrow[33] = "..#......................#####@@@.................................................................####@@@@@@@##.";
global.a2m1_mrow[34] = "..#@@@.....................##.@@@..............##############.@@@..........@@....................#####@@@@@@@##.";
global.a2m1_mrow[35] = "..#@@@........................@@@..............@@@@@@@@@@@@@@@@@@@........@@@@@.........@@@####..####@@@@@@@@##.";
global.a2m1_mrow[36] = "..@@@@.........................##.............#@@@@@@@@@@@@@@@@@@@@.......@@@@@........@@@@@####.###@@@@@@@@##..";
global.a2m1_mrow[37] = "..@@@@#........##...#...........#.......#######@@@@@@@@@@@@@@@@@@@@.......@@@@@........@@@@@########@@@@@####...";
global.a2m1_mrow[38] = "..@@@@.........####..............#..#####.......@@@@@@@@@@@@@@@@@@@...#####@@@####.....@@@@@########@@@@@##.....";
global.a2m1_mrow[39] = "..................................###........................@@@@@...##############.....@@@##########@@@##......";

var stx_r, stx_c, stx_ch, stx_v, stx_c0;
for (stx_r = 0; stx_r < global.a2m1_rows; stx_r += 1) {
    for (stx_c = 0; stx_c < global.a2m1_cols; stx_c += 1) {
        stx_ch = string_char_at(global.a2m1_mrow[stx_r], stx_c + 1);
        stx_v = 0;
        if (stx_ch = "#") stx_v = 1;
        if (stx_ch = "@") stx_v = 2;
        global.a2m1_g[stx_r * global.a2m1_cols + stx_c] = stx_v;
    }
}
// Row runs. Nothing draws these — they are the sampling table a lightning
// strike picks its two endpoints from, which is why they are runs and not
// cells: one random pick lands anywhere in the storm, uniformly by area.
global.a2m1_nsp = 0;
for (stx_r = 0; stx_r < global.a2m1_rows; stx_r += 1) {
    stx_c0 = -1;
    for (stx_c = 0; stx_c <= global.a2m1_cols; stx_c += 1) {
        stx_v = 0;
        if (stx_c < global.a2m1_cols) stx_v = global.a2m1_g[stx_r * global.a2m1_cols + stx_c];
        if (stx_v > 0) {
            if (stx_c0 < 0) stx_c0 = stx_c;
        } else {
            if (stx_c0 >= 0) {
                global.a2m1_spx[global.a2m1_nsp] = stx_c0 * global.a2m1_cellsz;
                global.a2m1_spy[global.a2m1_nsp] = stx_r * global.a2m1_cellsz;
                global.a2m1_spw[global.a2m1_nsp] = (stx_c - stx_c0) * global.a2m1_cellsz;
                global.a2m1_nsp += 1;
                stx_c0 = -1;
            }
        }
    }
}

// ------------------------------------------------------- the camera limit
if (!variable_global_exists('a2m1_ctl')) global.a2m1_ctl = 1;
if (!variable_global_exists('a2m1_clx')) { global.a2m1_clx = 0; global.a2m1_cly = 0; }
if (!variable_global_exists('a2m1_cll')) global.a2m1_cll = 0;
if (!variable_global_exists('a2m1_bounds')) global.a2m1_bounds = 0;
if (!variable_global_exists('a2m1_bx2')) global.a2m1_bx2 = 3600;
if (!variable_global_exists('a2m1_boundhook')) {
global.a2m1_boundhook = 1;
object_event_add(ctr_GUI, 3, 2,
    'if (global.a2m1_bounds = 1) {' +
    'if (room = global.act2_room1) {' +
    'var blim;' +
    'blim = global.a2m1_bx2 + GUI_MinimapSize * l_zoom - view_wview[0];' +
    'if (blim < 0) blim = 0;' +
    'if (l_viewx > blim) { view_xview[0] += blim - l_viewx; l_viewx = blim; }' +
    '}' +
    '}');

object_event_add(ctr_GUI, 3, 2,
    'if (room = global.act2_room1) {' +
    'if (global.a2m1_ctl = 0) {' +
    'if (global.a2m1_cll = 0) {' +
    'global.a2m1_clx = l_viewx; global.a2m1_cly = l_viewy;' +
    'if (!instance_exists(GUI_CamMover)) global.a2m1_cll = 1;' +
    '} else {' +
    'view_xview[0] += global.a2m1_clx - l_viewx; view_yview[0] += global.a2m1_cly - l_viewy;' +
    'l_viewx = global.a2m1_clx; l_viewy = global.a2m1_cly;' +
    '}' +
    'if (instance_exists(global.a2m1_ship)) with (global.a2m1_ship) {' +
    'l_movetox = x; l_movetoy = y; l_faceto = -1;' +
    'l_target = -4; l_facetarg = -4; alarm[8] = 0; l_holdposition = true;' +
    '}' +
    '} else {' +
    'global.a2m1_clx = l_viewx; global.a2m1_cly = l_viewy; global.a2m1_cll = 0;' +
    '}' +
    '}');

// The minimap half. Without it the camera limit hides nothing — ctr_GUI blips
// every ctr_Ship in the room, so a station the player cannot look at is still a
// cluster of squares in the corner. It is also what stops the limit reading as
// a bug: a camera that silently refuses to pan is broken, a camera that stops
// at a line the map draws is a door.
//
// Appended to Draw so it lands on top of the minimap ctr_GUI just drew.
//
// ⚠ The rect is re-derived here rather than read off ctr_GUI. `mapx1`, `mapx2`
// and `mapsizew` are ctr_GUI instance variables in the stock source — assigned
// in its Create and refreshed in its End Step — and reading them from an
// appended Draw action is still "Unknown variable mapx1", 1321 times in one
// sitting. Whatever owns them, it is not the instance this action runs on.
//
// So the geometry comes from what is legible from anywhere: the minimap is
// GUI_MinimapSize * global.l_zoom square, pinned to the top-right corner of the
// view, and a world x lands at that same fraction of it. That is the stock
// transform written out rather than borrowed, and it needs nothing but the view
// and the room.
object_event_add(ctr_GUI, 8, 0,
    'if (global.a2m1_bounds = 1) {' +
    'if (room = global.act2_room1) {' +
    'var mw, mx1, mx2, my1, fx;' +
    'mw = GUI_MinimapSize * global.l_zoom;' +
    'mx1 = view_xview[0] + view_wview[0] - mw;' +
    'mx2 = view_xview[0] + view_wview[0] - 1;' +
    'my1 = view_yview[0];' +
    'fx = mx1 + global.a2m1_bx2 * mw / room_width;' +
    'if (fx < mx2) {' +
    'draw_set_color(c_black);' +
    'draw_set_alpha(0.92);' +
    'draw_rectangle(fx, my1, mx2, my1 + mw, 0);' +
    'draw_set_alpha(1);' +
    'draw_set_color($00FF00);' +
    'draw_line(fx, my1, fx, my1 + mw);' +
    '}' +
    '}' +
    '}');
}
global.a2m1_bx2 = 3600;


// ------------------------------------------------------------- define once
// GM7 has no room_delete, so a room_add per reload would leak one every time.
//
// One guard per index rather than one around the lot: a mod that grows a new
// object has to be able to claim it in a session that is already running, and a
// single `if (!variable_global_exists(ctr))` around everything would skip the
// new line forever on exactly the reload that needed it.
if (!variable_global_exists('a2m1_stormobj')) global.a2m1_stormobj = object_add();
if (!variable_global_exists('a2m1_puffobj')) global.a2m1_puffobj = object_add();
if (!variable_global_exists('a2m1_ctr')) {
global.a2m1_ctr = object_add();
global.act2_room1 = room_add();
room_set_code(global.act2_room1,
    'instance_create(0,0,ctr_GUI); instance_create(0,0,' + string(global.a2m1_ctr) + ');');
// The view is authored once and never re-asserted. mods/resolution.gml rewrites
// every room's view port at startup to the picked resolution -- that is how the
// drawing region gets built at anything other than 1024x768 -- so a reload that
// set this again would drop the mission room, and only the mission room, back to
// 4:3 inside a widescreen window.
room_set_view(global.act2_room1, 0, 1, 0, 0, 1024, 768, 0, 0, 1024, 768, 32, 32, -1, -1, -1);
room_set_view_enabled(global.act2_room1, 1);
}

// ------------------------------------------------------- re-bind every load
object_event_clear(global.a2m1_stormobj, 0, 0);
object_event_add(global.a2m1_stormobj, 0, 0,
    'depth = 700;' +
    'l_bolt = 0; l_flash = 0; l_bn = 0; l_wcull = 0;' +
    'var sr, sc, sv, se, pd, pf;' +
    'for (sr = 0; sr < global.a2m1_rows; sr += 1) {' +
    'for (sc = 0; sc < global.a2m1_cols; sc += 1) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv > 0) {' +
    'se = 0;' +
    'if (sr = 0) se = 1;' +
    'if (sc = 0) se = 1;' +
    'if (sr = global.a2m1_rows - 1) se = 1;' +
    'if (sc = global.a2m1_cols - 1) se = 1;' +
    'if (se = 0) {' +
    'if (global.a2m1_g[(sr - 1) * global.a2m1_cols + sc] = 0) se = 1;' +
    'if (global.a2m1_g[(sr + 1) * global.a2m1_cols + sc] = 0) se = 1;' +
    'if (global.a2m1_g[sr * global.a2m1_cols + sc - 1] = 0) se = 1;' +
    'if (global.a2m1_g[sr * global.a2m1_cols + sc + 1] = 0) se = 1;' +
    '}' +
    'pd = global.a2m1_dens;' +
    'if (se = 1) pd = 0.5;' +
    'if (random(1) < pd) {' +
    'pf = instance_create(sc * global.a2m1_cellsz + random(global.a2m1_cellsz), sr * global.a2m1_cellsz + random(global.a2m1_cellsz), global.a2m1_puffobj);' +
    'if (sv = 2) pf.image_blend = make_color_rgb(255, 130 + random(60), 55 + random(45));' +
    '}' +
    '}' +
    '}' +
    '}' +
    'alarm[0] = 45 + random(90);');
object_event_clear(global.a2m1_stormobj, 3, 0);
object_event_add(global.a2m1_stormobj, 3, 0,
    'var sr, sc, sv, kh, khit;' +
    'if (global.ed_pause) exit;' +
    'if (l_bolt > 0) l_bolt -= 1;' +
    'if (l_flash > 0) l_flash -= 1;' +
    'if (global.a2m1_surge = 1) {' +
    'var wsp, wgap, wcol, wr, wc, wi, wdx, wdy, wsk, wpf;' +
    'wsp = 1.2;' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'wgap = global.a2m1_ship.x - global.a2m1_sx;' +
    'if (wgap > 800) wsp = wsp * 2.2;' +
    '}' +
    'global.a2m1_sx += wsp;' +
    'if (global.a2m1_sx > 2900) global.a2m1_sx = 2900;' +
    'for (wi = 0; wi < global.a2m1_nsh; wi += 1) {' +
    'if (global.a2m1_shon[wi] = 0) {' +
    'if (global.a2m1_sx > global.a2m1_shx[wi] - global.a2m1_shr - 140) global.a2m1_shon[wi] = 1;' +
    '}' +
    '}' +
    'wcol = floor(global.a2m1_sx / global.a2m1_cellsz);' +
    'if (global.a2m1_scol < 0) global.a2m1_scol = 0;' +
    'while (global.a2m1_scol <= wcol) {' +
    'wc = global.a2m1_scol;' +
    'global.a2m1_scol += 1;' +
    'if (wc < global.a2m1_cols) {' +
    'for (wr = 0; wr < global.a2m1_rows; wr += 1) {' +
    'wsk = 0;' +
    'for (wi = 0; wi < global.a2m1_nsh; wi += 1) {' +
    'if (global.a2m1_shon[wi] = 1) {' +
    'wdx = (wc + 0.5) * global.a2m1_cellsz - global.a2m1_shx[wi];' +
    'wdy = (wr + 0.5) * global.a2m1_cellsz - global.a2m1_shy[wi];' +
    'if (wdx * wdx + wdy * wdy < global.a2m1_shr * global.a2m1_shr) wsk = 1;' +
    '}' +
    '}' +
    'if (wsk = 0) {' +
    'global.a2m1_g[wr * global.a2m1_cols + wc] = 3;' +
    'if (random(1) < global.a2m1_dens) {' +
    'wpf = instance_create(wc * global.a2m1_cellsz + random(global.a2m1_cellsz), wr * global.a2m1_cellsz + random(global.a2m1_cellsz), global.a2m1_puffobj);' +
    'wpf.l_wall = 1;' +
    'wpf.image_blend = make_color_rgb(255, 90 + random(70), 40 + random(50));' +
    '}' +
    '}' +
    '}' +
    '}' +
    '}' +
    'l_wcull += 1;' +
    'if (l_wcull > 90) {' +
    'l_wcull = 0;' +
    'with (global.a2m1_puffobj) { if (l_wall = 1) { if (x < global.a2m1_sx - 1500) instance_destroy(); } }' +
    '}' +
    '}' +
    'for (kh = 0; kh < global.a2m1_nsh; kh += 1) {' +
    'if (global.a2m1_shf[kh] > 0) global.a2m1_shf[kh] -= 1;' +
    'khit = collision_circle(global.a2m1_shx[kh], global.a2m1_shy[kh], global.a2m1_shr, obs_Meteor, 0, 1);' +
    'if (khit != noone) {' +
    'with (khit) instance_destroy();' +
    'global.a2m1_shf[kh] = 12;' +
    '}' +
    '}' +
    'if (global.ed_edit) exit;' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'with (ShipSection) {' +
    'if (l_owner = global.a2m1_ship) {' +
    'sr = floor(y / global.a2m1_cellsz);' +
    'sc = floor(x / global.a2m1_cellsz);' +
    'if (sr >= 0) { if (sr < global.a2m1_rows) { if (sc >= 0) { if (sc < global.a2m1_cols) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv = 1) damage(global.a2m1_d1, id);' +
    'if (sv = 2) damage(global.a2m1_d2, id);' +
    'if (sv = 3) damage(global.a2m1_d3, id);' +
    '} } } }' +
    '}' +
    '}' +
    'sr = floor(global.a2m1_ship.y / global.a2m1_cellsz);' +
    'sc = floor(global.a2m1_ship.x / global.a2m1_cellsz);' +
    'if (sr >= 0) { if (sr < global.a2m1_rows) { if (sc >= 0) { if (sc < global.a2m1_cols) {' +
    'sv = global.a2m1_g[sr * global.a2m1_cols + sc];' +
    'if (sv = 1) damage(global.a2m1_d1, global.a2m1_ship);' +
    'if (sv = 2) damage(global.a2m1_d2, global.a2m1_ship);' +
    'if (sv = 3) damage(global.a2m1_d3, global.a2m1_ship);' +
    '} } } }' +
    '}');
object_event_clear(global.a2m1_stormobj, 8, 0);
object_event_add(global.a2m1_stormobj, 8, 0,
    'var vx, vy, vw, vh;' +
    'if (l_flash < 1) exit;' +
    'vx = view_xview[0]; vy = view_yview[0]; vw = view_wview[0]; vh = view_hview[0];' +
    'draw_set_blend_mode(bm_add);' +
    'with (global.a2m1_puffobj) {' +
    'if (x > vx - 500) { if (x < vx + vw + 500) { if (y > vy - 500) { if (y < vy + vh + 500) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,merge_color(image_blend,c_white,0.35),image_alpha * other.l_flash * 0.12);' +
    '} } } }' +
    '}' +
    'draw_set_alpha(1);' +
    'draw_set_blend_mode(bm_normal);');
object_event_clear(global.a2m1_puffobj, 0, 0);
object_event_add(global.a2m1_puffobj, 0, 0,
    'var ran;' +
    'sprite_index = spr_Nebula;' +
    'ran = random(1.2);' +
    'image_xscale = 1 + ran;' +
    'image_yscale = 1 + ran;' +
    'image_angle = random(360);' +
    'image_alpha = 0.13 + random(0.15);' +
    'image_blend = make_color_rgb(180 + random(75), 26 + random(46), 26 + random(34));' +
    'l_wall = 0;' +
    'l_lo = image_alpha;' +
    'l_hi = image_alpha + 0.15;' +
    'l_glow = 0.004 + random(0.006);' +
    'l_rotate = -0.25 + random(0.5);' +
    'l_curl = 0.4 + random(0.9);' +
    'if (random(1) < 0.5) l_curl = -l_curl;' +
    'direction = random(360);' +
    'speed = 0.02 + random(0.06);' +
    'depth = 150 + random(260);' +
    'alarm[0] = 1 + random(9);');
object_event_clear(global.a2m1_puffobj, 2, 0);
object_event_add(global.a2m1_puffobj, 2, 0,
    'image_alpha += l_glow;' +
    'if (image_alpha < l_lo) { image_alpha = l_lo; l_glow *= -1; }' +
    'if (image_alpha > l_hi) { image_alpha = l_hi; l_glow *= -1; }' +
    'image_angle += l_rotate;' +
    'direction += l_curl;' +
    'alarm[0] = 9;');
object_event_clear(global.a2m1_puffobj, 8, 0);
object_event_add(global.a2m1_puffobj, 8, 0,
    'if (x < view_xview[0] - 500) exit;' +
    'if (x > view_xview[0] + view_wview[0] + 500) exit;' +
    'if (y < view_yview[0] - 500) exit;' +
    'if (y > view_yview[0] + view_hview[0] + 500) exit;' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha);');
object_event_clear(global.a2m1_stormobj, 2, 0);
object_event_add(global.a2m1_stormobj, 2, 0,
    'var i, tries, sx, sy, ex, ey, nx, ny, dd, got, k;' +
    'alarm[0] = 45 + random(90);' +
    'if (global.ed_pause) exit;' +
    'if (global.a2m1_nsp < 1) exit;' +
    'got = 0; sx = 0; sy = 0; ex = 0; ey = 0;' +
    'for (tries = 0; tries < 24; tries += 1) {' +
    'if (got < 2) {' +
    'i = floor(random(global.a2m1_nsp));' +
    'nx = global.a2m1_spx[i] + random(global.a2m1_spw[i]);' +
    'ny = global.a2m1_spy[i] + random(global.a2m1_cellsz);' +
    'if (nx > view_xview[0]) { if (nx < view_xview[0] + view_wview[0]) {' +
    'if (ny > view_yview[0]) { if (ny < view_yview[0] + view_hview[0]) {' +
    'if (got = 0) { sx = nx; sy = ny; got = 1; }' +
    'else {' +
    'dd = point_distance(sx, sy, nx, ny);' +
    'if (dd > 150) { if (dd < 550) { ex = nx; ey = ny; got = 2; } }' +
    '}' +
    '} } } }' +
    '}' +
    '}' +
    'if (got < 2) exit;' +
    'l_bn = 7;' +
    'l_bx[0] = sx; l_by[0] = sy;' +
    'for (k = 1; k < l_bn; k += 1) {' +
    'l_bx[k] = sx + (ex - sx) * k / l_bn - 30 + random(60);' +
    'l_by[k] = sy + (ey - sy) * k / l_bn - 30 + random(60);' +
    '}' +
    'l_bx[l_bn] = ex; l_by[l_bn] = ey;' +
    'l_bolt = 4 + random(3);' +
    'l_flash = 9;');
object_event_clear(global.a2m1_ctr, 0, 0);
object_event_add(global.a2m1_ctr, 0, 0,
    'var s;' +
    'depth = -9;' +
    'global.gamecontroller = self.id;' +
    'l_messagecount = 0;' +
    'l_seek = 0; l_seek_from = 0;' +
    'l_temp = -4;' +
    'global.ed_beat = -1; global.ed_beatseq += 1;' +
    'global.a2m1_won = 0; global.a2m1_failed = 0; global.a2m1_meteors = 0;' +
    'global.a2m1_interf = 0;' +
    'global.a2m1_interfc = 0;' +
    'global.a2m1_surge = 0; global.a2m1_sx = 0; global.a2m1_scol = 0;' +
    'global.a2m1_bounds = 1;' +
    'global.a2m1_d3 = 2.5;' +
    'global.a2m1_shr = 88;' +
    'global.a2m1_nsh = 5;' +
    'global.a2m1_shx[0] = 724; global.a2m1_shy[0] = 1448; global.a2m1_shon[0] = 0; global.a2m1_shf[0] = 0;' +
    'global.a2m1_shx[1] = 1314; global.a2m1_shy[1] = 739; global.a2m1_shon[1] = 0; global.a2m1_shf[1] = 0;' +
    'global.a2m1_shx[2] = 1911; global.a2m1_shy[2] = 1222; global.a2m1_shon[2] = 0; global.a2m1_shf[2] = 0;' +
    'global.a2m1_shx[3] = 2269; global.a2m1_shy[3] = 741; global.a2m1_shon[3] = 0; global.a2m1_shf[3] = 0;' +
    'global.a2m1_shx[4] = 3120; global.a2m1_shy[4] = 1120; global.a2m1_shon[4] = 0; global.a2m1_shf[4] = 0;' +
    'if !variable_global_exists("l_fnames") then' +
    '{' +
    'global.l_fnames = ds_list_create();' +
    'global.l_objects[0] = -4;' +
    '}' +
    'global.jumpinships = false;' +
    'global.World_MaxRangeSqr = sqr(World_MaxRange);' +
    'stopMusic();' +
    's = instance_create(260,1000,Hestia);' +
    'global.a2m1_ship = s;' +
    'global.a2m1_ctl = 0;' +
    'if (global.a2m1_ctl = 0) s.l_myship = 0;' +
    '/* Unlatched on every entry, so the pin takes the camera this run actually has' +
    '   rather than one a previous run left in the global. centreCamera below is what' +
    '   it will latch onto. */' +
    'global.a2m1_cll = 0;' +
    'with (ShipSection) { if (l_owner = global.a2m1_ship) l_hp = l_hp * 0.55; }' +
    'repeat (16) { instance_create(random(room_width),random(room_height),ter_Nebula); }' +
    'instance_create(0,0,global.a2m1_stormobj);' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'alarm[2] = 45;');
object_event_clear(global.a2m1_ctr, 2, 2);
object_event_add(global.a2m1_ctr, 2, 2,
    'var s;' +
    'global.ed_beat = 0;' +
    'global.ed_beatseq += 1;' +
    'stopMusic();' +
    'sound_loop(snd_eeriesound);' +
    'global.a2m1_interf = 1; global.a2m1_interfc = 1;' +
    'centreCamera(260,1000,0);' +
    'global.lasteventx = 260; global.lasteventy = 1000;' +
    'global.a2m1_cll = 0;' +
    'global.a2m1_ctl = 0; if (instance_exists(global.a2m1_ship)) global.a2m1_ship.l_myship = 0; if (instance_exists(ctr_GUI)) ctr_GUI.l_numselected = 0;' +
    's = noone;' +
    'if (file_exists("mods/ships/beacon_ratline.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/beacon_ratline.shp",2,724,1448);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    's = instance_create(724,1448,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(s)) { s.l_holdposition = true; s.l_myship = 0; s.l_thrust = 0; s.l_maxspeed = 0; s.l_turning = 0; s.direction = 12; s.image_angle = 12; };' +
    's = noone;' +
    'if (file_exists("mods/ships/beacon_ratline_hulk.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/beacon_ratline_hulk.shp",2,1314,739);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    's = instance_create(1314,739,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(s)) { s.l_holdposition = true; s.l_myship = 0; s.l_thrust = 0; s.l_maxspeed = 0; s.l_turning = 0; s.direction = 61; s.image_angle = 61; };' +
    's = noone;' +
    'if (file_exists("mods/ships/beacon_ratline.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/beacon_ratline.shp",2,1911,1222);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    's = instance_create(1911,1222,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(s)) { s.l_holdposition = true; s.l_myship = 0; s.l_thrust = 0; s.l_maxspeed = 0; s.l_turning = 0; s.direction = 34; s.image_angle = 34; };' +
    's = noone;' +
    'if (file_exists("mods/ships/beacon_ratline_hulk.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/beacon_ratline_hulk.shp",2,2269,741);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    's = instance_create(2269,741,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(s)) { s.l_holdposition = true; s.l_myship = 0; s.l_thrust = 0; s.l_maxspeed = 0; s.l_turning = 0; s.direction = 78; s.image_angle = 78; };' +
    's = noone;' +
    'if (file_exists("mods/ships/beacon_ratline.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/beacon_ratline.shp",2,3120,1120);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    's = instance_create(3120,1120,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(s)) { s.l_holdposition = true; s.l_myship = 0; s.l_thrust = 0; s.l_maxspeed = 0; s.l_turning = 0; s.direction = 23; s.image_angle = 23; };' +
    'global.a2m1_gateN = noone;' +
    'if (file_exists("mods/ships/station_gatebattery.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/station_gatebattery.shp",2,3430,800);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_gateN = instance_create(3430,800,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_gateN)) { global.a2m1_gateN.l_holdposition = true; global.a2m1_gateN.l_myship = 0; global.a2m1_gateN.l_thrust = 0; global.a2m1_gateN.l_maxspeed = 0; global.a2m1_gateN.l_turning = 0; global.a2m1_gateN.direction = 205; global.a2m1_gateN.image_angle = 205; };' +
    'global.a2m1_gateS = noone;' +
    'if (file_exists("mods/ships/station_gatebattery.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/station_gatebattery.shp",2,3430,1290);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_gateS = instance_create(3430,1290,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_gateS)) { global.a2m1_gateS.l_holdposition = true; global.a2m1_gateS.l_myship = 0; global.a2m1_gateS.l_thrust = 0; global.a2m1_gateS.l_maxspeed = 0; global.a2m1_gateS.l_turning = 0; global.a2m1_gateS.direction = 155; global.a2m1_gateS.image_angle = 155; };' +
    'global.a2m1_station = noone;' +
    'if (file_exists("mods/ships/station_bolthole.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/station_bolthole.shp",2,4450,914);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_station = instance_create(4450,914,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_station)) { global.a2m1_station.l_holdposition = true; global.a2m1_station.l_myship = 0; global.a2m1_station.l_thrust = 0; global.a2m1_station.l_maxspeed = 0; global.a2m1_station.l_turning = 0; global.a2m1_station.direction = 180; global.a2m1_station.image_angle = 180; };' +
    'instance_create(3810,1228,ter_Planet);' +
    'global.a2m1_berth1 = instance_create(4056,1392,Hecate); global.a2m1_berth1.l_holdposition = true; global.a2m1_berth1.l_myship = 0; global.a2m1_berth1.l_thrust = 0; global.a2m1_berth1.l_maxspeed = 0; global.a2m1_berth1.l_turning = 0; global.a2m1_berth1.direction = 0; global.a2m1_berth1.image_angle = 0;' +
    'global.a2m1_berth2 = instance_create(4124,1194,Cronus); global.a2m1_berth2.l_holdposition = true; global.a2m1_berth2.l_myship = 0; global.a2m1_berth2.l_thrust = 0; global.a2m1_berth2.l_maxspeed = 0; global.a2m1_berth2.l_turning = 0; global.a2m1_berth2.direction = 0; global.a2m1_berth2.image_angle = 0;' +
    'global.a2m1_berth3 = instance_create(4056,622,Athena); global.a2m1_berth3.l_holdposition = true; global.a2m1_berth3.l_myship = 0; global.a2m1_berth3.l_thrust = 0; global.a2m1_berth3.l_maxspeed = 0; global.a2m1_berth3.l_turning = 0; global.a2m1_berth3.direction = 0; global.a2m1_berth3.image_angle = 0;' +
    'global.a2m1_berth4 = instance_create(4148,446,Hestia); global.a2m1_berth4.l_holdposition = true; global.a2m1_berth4.l_myship = 0; global.a2m1_berth4.l_thrust = 0; global.a2m1_berth4.l_maxspeed = 0; global.a2m1_berth4.l_turning = 0; global.a2m1_berth4.direction = 0; global.a2m1_berth4.image_angle = 0;' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t21,spr_MesHint);');
object_event_clear(global.a2m1_ctr, 2, 3);
object_event_add(global.a2m1_ctr, 2, 3,
    'event_user(0);');
object_event_clear(global.a2m1_ctr, 2, 5);
object_event_add(global.a2m1_ctr, 2, 5,
    'if (global.a2m1_meteors = 1) {' +
    'if (instance_number(obs_Meteor) < 48) {' +
    'if (instance_exists(global.a2m1_ship)) {' +
    'var mm, px, py, ba, sl, sh;' +
    'px = global.a2m1_ship.x; py = global.a2m1_ship.y;' +
    'ba = min(py - 500, view_yview[0] - 64);' +
    'sl = min(px - 400, view_xview[0]);' +
    'sh = max(px + 400, view_xview[0] + view_wview[0]);' +
    'sl = max(sl, 0); sh = min(sh, 3430);' +
    'if (sh > sl) {' +
    'mm = instance_create(sl + random(sh - sl), ba - random(300), obs_Meteor);' +
    'mm.direction = 240 + random(60);' +
    'mm.speed = 1 + random(1.2);' +
    'mm.image_xscale = 0.5 + random(0.4);' +
    'mm.image_yscale = mm.image_xscale;' +
    '}' +
    '}' +
    '}' +
    'alarm[5] = 35;' +
    '}');
object_event_clear(global.a2m1_ctr, 3, 0);
object_event_add(global.a2m1_ctr, 3, 0,
    'if (global.ed_edit) exit;' +
    'if (global.a2m1_won = 0) {' +
    'if (global.a2m1_failed = 0) {' +
    'if (!instance_exists(global.a2m1_ship)) {' +
    'global.a2m1_failed = 1;' +
    'centreCamera(global.lasteventx,global.lasteventy,0);' +
    'missionFail(global.a2m1_t22);' +
    '}' +
    '}' +
    '}');
object_event_clear(global.a2m1_ctr, 7, 10);
object_event_add(global.a2m1_ctr, 7, 10,
    'var g, s;' +
    'if (l_messagecount = 1) {' +
    'global.ed_beat = 1;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t0,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 2) {' +
    'global.ed_beat = 2;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"[Hint]",global.a2m1_t1,spr_MesHint);' +
    '}' +
    'else if (l_messagecount = 3) {' +
    'global.ed_beat = 3;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_ctl = 1; if (instance_exists(global.a2m1_ship)) { global.a2m1_ship.l_myship = 1; global.a2m1_ship.l_holdposition = false; };' +
    'global.a2m1_meteors = 1; alarm[5] = 1;' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t2,spr_MesObj);' +
    'g = instance_create(724,1448,MoveToArea); g.l_target = global.a2m1_ship; showPing(724,1448);' +
    '}' +
    'else if (l_messagecount = 5) {' +
    'global.ed_beat = 5;' +
    'global.ed_beatseq += 1;' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t3,spr_MesMan1);' +
    'g = instance_create(1314,739,MoveToArea); g.l_target = global.a2m1_ship; showPing(1314,739);' +
    '}' +
    'else if (l_messagecount = 7) {' +
    'global.ed_beat = 7;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t4,spr_MesMan1);' +
    'g = instance_create(1911,1222,MoveToArea); g.l_target = global.a2m1_ship; showPing(1911,1222);' +
    '}' +
    'else if (l_messagecount = 9) {' +
    'global.ed_beat = 9;' +
    'global.ed_beatseq += 1;' +
    'stopMusic(); bgm_Play(global.mus_battle,1);' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'global.a2m1_surge = 1; global.a2m1_sx = global.a2m1_ship.x - 900; global.a2m1_scol = floor(global.a2m1_sx / global.a2m1_cellsz);' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t5,spr_MesMan1);' +
    'g = instance_create(2269,741,MoveToArea); g.l_target = global.a2m1_ship; showPing(2269,741);' +
    '}' +
    'else if (l_messagecount = 11) {' +
    'global.ed_beat = 11;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t6,spr_MesMan1);' +
    'g = instance_create(3120,1120,MoveToArea); g.l_target = global.a2m1_ship; showPing(3120,1120);' +
    '}' +
    'else if (l_messagecount = 13) {' +
    'global.ed_beat = 13;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,c_red,"Bolthole Approach",global.a2m1_t7,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 14) {' +
    'global.ed_beat = 14;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Helm",global.a2m1_t8,spr_MesMan1);' +
    '}' +
    'else if (l_messagecount = 15) {' +
    'global.ed_beat = 15;' +
    'global.ed_beatseq += 1;' +
    'if (global.difficulty != World_Hard) saveGame();' +
    'global.a2m1_meteors = 0;' +
    'showMessage(0,$00FF00,"Bolthole Approach",global.a2m1_t9,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 16) {' +
    'global.ed_beat = 16;' +
    'global.ed_beatseq += 1;' +
    'stopMusic(); bgm_Play(global.mus_theme,1);' +
    'sound_stop(snd_eeriesound);' +
    'global.a2m1_interf = 0; global.a2m1_interfc = 1;' +
    'centreCamera(4297,917,90);' +
    'global.lasteventx = 4297; global.lasteventy = 917;' +
    'global.a2m1_cll = 0;' +
    'if (instance_exists(ctr_GUI)) ctr_GUI.l_zoomtar = 1.55;' +
    'global.a2m1_bounds = 0;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t10,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 17) {' +
    'global.ed_beat = 17;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t11,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 18) {' +
    'global.ed_beat = 18;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet HQ",global.a2m1_t12,spr_MesHQ);' +
    '}' +
    'else if (l_messagecount = 19) {' +
    'global.ed_beat = 19;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t13,spr_MesHong);' +
    'g = instance_create(4174,936,MoveToArea); g.l_target = global.a2m1_ship; showPing(4174,936);' +
    '}' +
    'else if (l_messagecount = 21) {' +
    'global.ed_beat = 21;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_hestiax = noone;' +
    'if (file_exists("mods/ships/hestia_x_erebus.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/hestia_x_erebus.shp",2,3968,942);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_hestiax = instance_create(3968,942,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_hestiax)) { global.a2m1_hestiax.direction = 90; global.a2m1_hestiax.image_angle = 90; };' +
    'showPing(3968,942);' +
    'with (global.a2m1_hestiax) { l_cloak_lock = 1; l_cloak_want = 0; l_cloak_snap = 0; };' +
    'l_messagecount = 22; alarm[3] = 75;' +
    '}' +
    'else if (l_messagecount = 22) {' +
    'global.ed_beat = 22;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t14,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 23) {' +
    'global.ed_beat = 23;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t15,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 24) {' +
    'global.ed_beat = 24;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t16,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 25) {' +
    'global.ed_beat = 25;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t17,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 26) {' +
    'global.ed_beat = 26;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t18,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 27) {' +
    'global.ed_beat = 27;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,c_red,"New Objective",global.a2m1_t19,spr_MesObj);' +
    '}' +
    'else if (l_messagecount = 28) {' +
    'global.ed_beat = 28;' +
    'global.ed_beatseq += 1;' +
    'showMessage(0,$00FF00,"Fleet Admiral Hong",global.a2m1_t20,spr_MesHong);' +
    '}' +
    'else if (l_messagecount = 29) {' +
    'global.ed_beat = 29;' +
    'global.ed_beatseq += 1;' +
    'global.a2m1_won = 1; missionSucc();' +
    '}');
object_event_clear(global.a2m1_ctr, 7, 11);
object_event_add(global.a2m1_ctr, 7, 11,
    'var s;' +
    'if (l_seek >= 3) { if (l_seek_from < 3) {' +
    'global.a2m1_ctl = 1; if (instance_exists(global.a2m1_ship)) { global.a2m1_ship.l_myship = 1; global.a2m1_ship.l_holdposition = false; };' +
    'global.a2m1_meteors = 1; alarm[5] = 1;' +
    '} }' +
    'if (l_seek >= 9) { if (l_seek_from < 9) {' +
    'stopMusic(); bgm_Play(global.mus_battle,1);' +
    'global.a2m1_surge = 1; global.a2m1_sx = global.a2m1_ship.x - 900; global.a2m1_scol = floor(global.a2m1_sx / global.a2m1_cellsz);' +
    '} }' +
    'if (l_seek >= 15) { if (l_seek_from < 15) {' +
    'global.a2m1_meteors = 0;' +
    '} }' +
    'if (l_seek >= 16) { if (l_seek_from < 16) {' +
    'stopMusic(); bgm_Play(global.mus_theme,1);' +
    'sound_stop(snd_eeriesound);' +
    'global.a2m1_interf = 0; global.a2m1_interfc = 1;' +
    'centreCamera(4297,917,90);' +
    'global.lasteventx = 4297; global.lasteventy = 917;' +
    'global.a2m1_cll = 0;' +
    'if (instance_exists(ctr_GUI)) ctr_GUI.l_zoomtar = 1.55;' +
    'global.a2m1_bounds = 0;' +
    '} }' +
    'if (l_seek >= 21) { if (l_seek_from < 21) {' +
    'global.a2m1_hestiax = noone;' +
    'if (file_exists("mods/ships/hestia_x_erebus.shp")) {' +
    'with (ctr_Spawner) instance_destroy();' +
    'global.a2m1_imp = importShip("mods/ships/hestia_x_erebus.shp",2,3968,942);' +
    'with (ctr_Spawner) instance_destroy();' +
    'if (global.a2m1_imp >= 0) {' +
    'global.a2m1_hestiax = instance_create(3968,942,global.a2m1_imp);' +
    '}' +
    '}' +
    'if (instance_exists(global.a2m1_hestiax)) { global.a2m1_hestiax.direction = 90; global.a2m1_hestiax.image_angle = 90; };' +
    'with (global.a2m1_hestiax) { l_cloak_lock = 1; l_cloak_want = 0; l_cloak_snap = 0; };' +
    '} }' +
    'l_seek_from = l_seek;' +
    'global.ed_beat = l_seek;' +
    'global.ed_beatseq += 1;' +
    'if (l_seek = 1) l_messagecount = 2;' +
    'else if (l_seek = 2) l_messagecount = 3;' +
    'else if (l_seek = 3) l_messagecount = 5;' +
    'else if (l_seek = 5) l_messagecount = 7;' +
    'else if (l_seek = 7) l_messagecount = 9;' +
    'else if (l_seek = 9) l_messagecount = 11;' +
    'else if (l_seek = 11) l_messagecount = 13;' +
    'else if (l_seek = 13) l_messagecount = 14;' +
    'else if (l_seek = 14) l_messagecount = 15;' +
    'else if (l_seek = 15) l_messagecount = 16;' +
    'else if (l_seek = 16) l_messagecount = 17;' +
    'else if (l_seek = 17) l_messagecount = 18;' +
    'else if (l_seek = 18) l_messagecount = 19;' +
    'else if (l_seek = 19) l_messagecount = 21;' +
    'else if (l_seek = 21) l_messagecount = 22;' +
    'else if (l_seek = 22) l_messagecount = 23;' +
    'else if (l_seek = 23) l_messagecount = 24;' +
    'else if (l_seek = 24) l_messagecount = 25;' +
    'else if (l_seek = 25) l_messagecount = 26;' +
    'else if (l_seek = 26) l_messagecount = 27;' +
    'else if (l_seek = 27) l_messagecount = 28;' +
    'else if (l_seek = 28) l_messagecount = 29;' +
    'else if (l_seek = 29) l_messagecount = 30;');
object_event_clear(global.a2m1_ctr, 8, 0);
object_event_add(global.a2m1_ctr, 8, 0,
    'var vx, vy, vw, vh, i, shx, shy, shr, shp, shf, shs;' +
    'vx = view_xview[0]; vy = view_yview[0]; vw = view_wview[0]; vh = view_hview[0];' +
    'with (global.a2m1_stormobj) {' +
    'if (l_bolt > 0) {' +
    'draw_set_blend_mode(bm_add);' +
    'draw_set_color(make_color_rgb(255, 70, 55));' +
    'draw_set_alpha(0.20);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 24); }' +
    'draw_set_color(make_color_rgb(255, 140, 110));' +
    'draw_set_alpha(0.45);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 8); }' +
    'draw_set_color(make_color_rgb(255, 242, 228));' +
    'draw_set_alpha(0.95);' +
    'for (i = 0; i < l_bn; i += 1) { draw_line_width(l_bx[i], l_by[i], l_bx[i + 1], l_by[i + 1], 2); }' +
    'draw_set_alpha(1);' +
    'draw_set_blend_mode(bm_normal);' +
    '}' +
    '}' +
    'if (global.a2m1_nsh > 0) {' +
    'draw_set_circle_precision(48);' +
    'draw_set_blend_mode(bm_add);' +
    'for (i = 0; i < global.a2m1_nsh; i += 1) {' +
    'shf = global.a2m1_shf[i] / 12;' +
    'shs = 0;' +
    'if (global.a2m1_shon[i] = 1) shs = 1;' +
    'if (shs + shf > 0) {' +
    'shx = global.a2m1_shx[i]; shy = global.a2m1_shy[i]; shr = global.a2m1_shr;' +
    'if (shx > vx - shr) { if (shx < vx + vw + shr) {' +
    'if (shy > vy - shr) { if (shy < vy + vh + shr) {' +
    'shp = 0.55 + 0.45 * sin(current_time / 260 + i * 1.7);' +
    'shr = shr + shf * 7;' +
    'draw_set_alpha(shs * (0.10 + 0.06 * shp) + 0.30 * shf);' +
    'draw_circle_color(shx, shy, shr, make_color_rgb(0, 0, 0), make_color_rgb(30 + 150 * shf, 90 + 70 * shp + 110 * shf, 150 + 90 * shp + 60 * shf), 0);' +
    'draw_set_color(make_color_rgb(165 + 80 * shf, 225, 255));' +
    'draw_set_alpha(shs * (0.40 + 0.28 * shp) + 0.55 * shf);' +
    'draw_circle(shx, shy, shr, true);' +
    'draw_set_alpha(1);' +
    '} } } }' +
    '}' +
    '}' +
    'draw_set_blend_mode(bm_normal);' +
    '}' +
    'if (global.a2m1_interfc = 1) {' +
    'draw_set_blend_mode(bm_add);' +
    'with (ter_Nebula) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha + random(0.4));' +
    '}' +
    'with (global.a2m1_puffobj) {' +
    'if (x > vx - 500) { if (x < vx + vw + 500) { if (y > vy - 500) { if (y < vy + vh + 500) {' +
    'draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha * (0.6 + random(0.9)));' +
    '} } } }' +
    '}' +
    'draw_set_blend_mode(bm_normal);' +
    '}' +
    'if (global.a2m1_interf = 1) {' +
    'with (ShipSection) {' +
    'draw_sprite_ext(sprite_index,image_index,xprevious - 4 + random(8),yprevious - 4 + random(8),image_xscale * (1 + random(0.22)),image_yscale * (1 + random(0.22)),image_angle,l_colour,image_alpha / 2);' +
    '}' +
    '}');

room_set_width(global.act2_room1, 5600);
room_set_height(global.act2_room1, 2000);
room_set_caption(global.act2_room1, "Bolthole");
room_set_background_color(global.act2_room1, c_black, 1);
