#!/usr/bin/env python3
"""PROTOTYPE runner — mission editor / beat editor UI variations.

    python3 prototype/mission-editor/run.py

Regenerates mission_data.js from the real Act II beat script, indexes the game's
sprites straight out of BattleshipsForever.exe **in memory**, serves this
directory, and opens the browser.

Game art is never written to disk. The exe is decrypted into RAM at startup
(~50 ms), sprite headers are indexed, and a frame is inflated + PNG-encoded the
first time the editor asks for it. Derived art therefore cannot be committed by
accident — there is no file. The editor degrades to vector shapes if the game is
not found, so the page still works without it.

    --yaml PATH   use another mission yaml
    --game DIR    game directory (default: $BSF_GAME_DIR, then the research tree)
    --port N      default 8777
    --no-open     just serve
"""
import functools
import http.server
import json
import os
import socketserver
import sys
import time
import urllib.parse
import webbrowser

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import assets as A                                                   # noqa: E402

DEFAULT_YAML = os.path.abspath(os.path.join(
    HERE, "..", "..", "campaign", "missions", "ep9.yaml"))

LIB = None          # assets.Library, or None when the game is not around
OBJ_SPRITES = {}
SHIPS = {}          # name -> parsed hull, memoised


def regen(path):
    """ep9.yaml -> mission_data.js (MISSION as parsed, plus the raw source)."""
    try:
        import yaml
    except ImportError:
        print("! PyYAML missing — keeping the existing mission_data.js snapshot")
        return
    if not os.path.exists(path):
        print(f"! {path} not found — keeping the existing snapshot")
        return
    raw = open(path, encoding="utf-8").read()
    m = yaml.safe_load(raw)
    m["_src"] = os.path.basename(path)
    with open(os.path.join(HERE, "mission_data.js"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by run.py from %s — do not edit.\n" % os.path.basename(path))
        f.write("window.MISSION = " + json.dumps(m, indent=1) + ";\n")
        f.write("window.MISSION_YAML = " + json.dumps(raw) + ";\n")
    print(f"regenerated mission_data.js from {path} ({len(m['beats'])} beats)")


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=HERE, **kw)

    def log_message(self, *a):
        pass

    def _send(self, body, ctype, cache=True):
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        if cache:
            self.send_header("Cache-Control", "max-age=3600")
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj):
        self._send(json.dumps(obj).encode(), "application/json", cache=False)

    def do_GET(self):
        u = urllib.parse.urlparse(self.path)
        parts = [p for p in u.path.split("/") if p]
        if parts[:1] != ["api"]:
            return super().do_GET()

        if parts[1:2] == ["assets"]:
            if not LIB:
                return self._json({"ok": False, "why": "game not found"})
            return self._json({"ok": True, "source": os.path.basename(LIB.source),
                               "sprites": LIB.manifest(), "objects": OBJ_SPRITES})

        if parts[1:2] == ["sprite"] and len(parts) > 2:
            name = urllib.parse.unquote(parts[2])
            frame = int(dict(urllib.parse.parse_qsl(u.query)).get("f", 0))
            if not LIB or name not in LIB.sprites:
                self.send_error(404, "no such sprite")
                return
            try:
                return self._send(LIB.png(name, frame), "image/png")
            except Exception as e:                                   # noqa: BLE001
                self.send_error(500, str(e))
                return

        if parts[1:2] == ["ship"] and len(parts) > 2:
            name = urllib.parse.unquote(parts[2])
            if name not in SHIPS:
                SHIPS[name] = A.ship(name)
            if not SHIPS[name]:
                self.send_error(404, "no hull dump")
                return
            return self._json(SHIPS[name])

        self.send_error(404)


def main():
    global LIB, OBJ_SPRITES
    argv = sys.argv[1:]

    def opt(name, default=None):
        return argv[argv.index(name) + 1] if name in argv else default

    regen(os.path.expanduser(opt("--yaml", DEFAULT_YAML)))

    try:
        t0 = time.time()
        LIB = A.Library.from_game(opt("--game")).classify()
        OBJ_SPRITES = A.object_sprites()
        masks = sum(1 for s in LIB.sprites.values() if s["mask"])
        print(f"indexed {len(LIB.sprites)} sprites in memory from "
              f"{os.path.basename(LIB.source)} in {time.time() - t0:.2f}s "
              f"({masks} palette masks, {len(OBJ_SPRITES)} object bindings)")
    except Exception as e:                                           # noqa: BLE001
        print(f"! no game art ({e}) — the editor will fall back to vector shapes")

    port = int(opt("--port", 8777))
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), Handler) as srv:
        url = f"http://127.0.0.1:{port}/?variant=1"
        print(f"\n  prototype: {url}")
        print("  editing models:  1 inspector · 2 direct · 3 command   ([ and ] to switch)")
        print("  round-one shapes: ?variant=A|B|C|D          ctrl-c to stop\n")
        if "--no-open" not in argv:
            webbrowser.open(url)
        try:
            srv.serve_forever()
        except KeyboardInterrupt:
            print()


if __name__ == "__main__":
    main()
